sudo: required
services:
    - docker
language: c

before_install:
    - docker build -t $DOCKER_USERNAME/testtravis .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/testtravis 

notifications:
    on_success: always
    on_failure: always


script: make test
