sudo: required
services:
    - docker
language: c

before_install:
    - docker build -t testTravis .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push 

notifications:
    on_success: always
    on_failure: always


script: make test
