language: ruby

before_install:
    - cp .env-example .env
    - cp env_rake.example.yml  env_rake.yml

build:
    script:
        - echo "testing ..."
        - echo $hola
#install_gems:
#    - gem install bundler
#    - bundle config geminabox.dapp.bc-fg.com buyco:$GEMINABOX_PASSWORD 
#    - bundle install 
