sudo: required
services:
    - docker
language: c


notifications:
    on_success: always
    on_failure: always


script: make test
    
after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t $DOCKER_USERNAME/travis . ;
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push $DOCKER_USERNAME/travis;
      fi

